# Generated by Django 4.2.1 on 2023-07-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("route", models.CharField(max_length=50)),
            ],
        ),
    ]
